### ISSUE TITLE
复现：Gradio端口问题

### ISSUE THREAD

**Issue by xjohn157** [Warma10032/cyber-doctor#8]
2025-05-16 12:27:11,213 - modelscope - WARNING - No preprocessor field found in cfg.
2025-05-16 12:27:11,213 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2025-05-16 12:27:11,214 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'W:/xinjian111/.cache/modelscope/hub/iic/nlp_corom_sentence-embedding_chinese-base'}. trying to build by task and model information.
2025-05-16 12:27:11,262 - modelscope - INFO - cuda is not available, using cpu instead.
2025-05-16 12:27:11,267 - modelscope - WARNING - No preprocessor field found in cfg.
2025-05-16 12:27:11,268 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2025-05-16 12:27:11,268 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'W:/xinjian111/.cache/modelscope/hub/iic/nlp_corom_sentence-embedding_chinese-base', 'sequence_length': 128}. trying to build by task and model information.
2025-05-16 12:27:18,966 - modelscope - WARNING - Model revision not specified, use revision: v1.1.0
Downloading Model from https://www.modelscope.cn to directory: C:\Users\Noisyly\.cache\modelscope\hub\models\iic\nlp_corom_sentence-embedding_chinese-base
2025-05-16 12:27:24,125 - modelscope - WARNING - Model revision not specified, use revision: v1.1.0
2025-05-16 12:27:24,743 - modelscope - INFO - initiate model from C:\Users\Noisyly\.cache\modelscope\hub\models\iic\nlp_corom_sentence-embedding_chinese-base
2025-05-16 12:27:24,743 - modelscope - INFO - initiate model from location C:\Users\Noisyly\.cache\modelscope\hub\models\iic\nlp_corom_sentence-embedding_chinese-base.
2025-05-16 12:27:24,747 - modelscope - INFO - initialize model from C:\Users\Noisyly\.cache\modelscope\hub\models\iic\nlp_corom_sentence-embedding_chinese-base
2025-05-16 12:27:25,418 - modelscope - WARNING - No preprocessor field found in cfg.
2025-05-16 12:27:25,418 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2025-05-16 12:27:25,418 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\Noisyly\\.cache\\modelscope\\hub\\models\\iic\\nlp_corom_sentence-embedding_chinese-base'}. trying to build by task and model information.
2025-05-16 12:27:25,457 - modelscope - INFO - cuda is not available, using cpu instead.
2025-05-16 12:27:25,461 - modelscope - WARNING - No preprocessor field found in cfg.
2025-05-16 12:27:25,462 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2025-05-16 12:27:25,462 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\Noisyly\\.cache\\modelscope\\hub\\models\\iic\\nlp_corom_sentence-embedding_chinese-base', 'sequence_length': 128}. trying to build by task and model information.
W:\xinjian111\cyber-doctor\app.py:491: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style dictionaries with 'role' and 'content' keys.
  chatbot = gr.Chatbot(
* Running on local URL:  http://0.0.0.0:10032
Traceback (most recent call last):
  File "W:\xinjian111\cyber-doctor\app.py", line 566, in <module>
    start_gradio()
  File "W:\xinjian111\cyber-doctor\app.py", line 562, in start_gradio
    demo.launch(server_name="0.0.0.0",server_port=10032, share=True)
  File "W:\xinjian111\anaconda3\envs\myenv\lib\site-packages\gradio\blocks.py", line 2717, in launch
    raise Exception(
Exception: Couldn't start the app because 'http://localhost:10032/gradio_api/startup-events' failed (code 502). Check your network or proxy settings to ensure localhost is accessible.

佬，他说Gradio接不上端口，这个该怎么解决呢？

**Comment by Warma10032** [comment]
关闭梯子试试

**Comment by xjohn157** [comment]
> 关闭梯子试试
W:\xinjian111\cyber-doctor\app.py:495: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style dictionaries with 'role' and 'content' keys.
  chatbot = gr.Chatbot(
* Running on local URL:  http://0.0.0.0:10032

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

佬，关了我试了几次都是这样，是我网络问题吗，我换了热点和移动wifi可能网不是很好，而且我也把他要的文件frpc_windows_amd64_v0.3下到指定地址了，佬知道有什么解决办法吗

**Comment by xjohn157** [comment]
* Running on local URL:  http://0.0.0.0:10032
* To create a public link, set `share=True` in `launch()`.

如果是按原来的代码，他就会让把share=True

**Comment by Warma10032** [comment]
URL可以改改，可以改成127.0.0.1或者改端口号试试

**Comment by xjohn157** [comment]
> URL可以改改，可以改成127.0.0.1或者改端口号试试

* Running on local URL:  http://127.0.0.1:40000

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

很奇怪就，感觉可能是我的网络问题

**Comment by xjohn157** [comment]
解决了佬，我换了台电脑，在那上面跑起来了，但是不是在复现流程上的端口，是在他url端口跑起来了OuO
